version: '3'
services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - "3306:3306"
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    command: rails server -p 3000
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
