version: '3'
services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - "3306:3306"
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    command: sh -c "rm -f /app/tmp/pids/server.pid && rails server -p 3000 -b '0.0.0.0'"
    environment:
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - bundle:/usr/local/bundle
      - /app/node_modules
      - ./app:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  bundle:
